Battle com with server
cs-24-sw-2-07/client pull request #30
Opened 2024-05-02 13:38 UTC by ChristianSteen-SW23

fixed #21

2024-05-05 20:47 UTC, SimonStjernholm commented on src/App.jsx
>          };
når vi laver de her socket.on / socket.off, så skal vi nok lige huske at bruge samme casing. F.eks. socket.on("lobby") eksisterer, men socket.off("Lobby") bliver kaldt. Ved ikke om det er case-sensitive, men er det sikkert?

Ikke noget vi behøver at ændre nu her, da vi skal have kigget alt kode igennem og lavet sådan nogle ændringer til sidst, der er flere steder det halter med casing af variabler etc.

2024-05-05 21:11 UTC, SimonStjernholm requested changes
tænker det er super fint, vi burde måske overveje om alle console.logs er nødvendige, og om det er noget vi vil have med i vores færdige build, har tilføjet et par comments jeg lige synes i skal kigge på. :)

Efter en hurtig søgning findes der en npm pakke som er et Vite plugin, som gør at console.log bliver fjernet ved production builds `npm run build`. Dette kan potentielt være en løsning hvis vi gerne vil beholde console.logs?
https://www.npmjs.com/package/vite-plugin-remove-console

2024-05-05 21:11 UTC, SimonStjernholm commented on src/components/battleComponets/DisplayButtons.jsx
> +                    <button type="button" className="btn btn-success p-3"id="voteBtn" onClick={()=>{socket.emit("answerReview",{value:false});props.setHideElement(true)}}>wrong!</button>
For my sanity, please tilføj lidt mellemrum så det er lidt mere læsbart :) Det behøver ikke alt at være så kompakt som muligt, det sørger Vite for at gøre når man bygger til "production" ved `npm run build` :)
```suggestion
                    <button type="button" className="btn btn-success p-3" id="voteBtn" onClick={()=>{socket.emit("answerReview", {value: true}); props.setHideElement(true)}}>correct!</button>
                    <button type="button" className="btn btn-success p-3" id="voteBtn" onClick={()=>{socket.emit("answerReview", {value: false}); props.setHideElement(true)}}>wrong!</button>
```

2024-05-05 21:11 UTC, SimonStjernholm commented on src/components/battleComponets/DisplayButtons.jsx
> +                <button type="button" className="btn btn-success"id="readyBtn" onClick={()=>{socket.emit("doneAnswering"); props.setShowAnswer(true); props.setHideElement(true)}}>Done answering? clic
```suggestion
                <button type="button" className="btn btn-success" id="readyBtn" onClick={()=>{socket.emit("doneAnswering"); props.setShowAnswer(true); props.setHideElement(true)}}>Done answering? click here</button>
```

2024-05-05 21:11 UTC, SimonStjernholm commented on src/components/battleComponets/DisplayLives.jsx
> +
Hvis jeg skulle have gjort det, ville jeg nok have haft serveren til at sende liv for begge personer under ét event, og derved kun have haft brug for at have en state der havde holdt begge, så sparer man lidt logik, men dette er fint :)

2024-05-06 11:30 UTC, SimonStjernholm approved these changes

2024-05-06 11:31 UTC, merged

2024-05-13 07:27 UTC, ChristianSteen-SW23 reviewed
lgtm